# Generated by Django 5.2.7 on 2025-10-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('icone', models.CharField(blank=True, choices=[('pix', 'fas fa-qrcode'), ('cartao', 'fas fa-credit-card'), ('boleto', 'fas fa-barcode'), ('paypal', 'fab fa-paypal'), ('transferencia', 'fas fa-university'), ('dinheiro', 'fas fa-money-bill-wave'), ('local', 'fas fa-store')], max_length=100, null=True)),
            ],
        ),
    ]
