# Generated by Django 5.2.7 on 2025-10-26 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, max_length=100)),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('icone', models.CharField(choices=[('pix', 'fas fa-qrcode'), ('cartao', 'fas fa-credit-card'), ('boleto', 'fas fa-barcode'), ('paypal', 'fab fa-paypal'), ('transferencia', 'fas fa-university'), ('dinheiro', 'fas fa-money-bill-wave'), ('local', 'fas fa-store')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='icone',
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagamento.metodo'),
        ),
    ]
