# Generated by Django 5.2.1 on 2025-11-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0003_cupom_pagamento_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodo',
            name='icone',
            field=models.CharField(choices=[('fas fa-qrcode', 'PIX'), ('fas fa-credit-card', 'Cartão'), ('fas fa-barcode', 'Boleto'), ('fab fa-paypal', 'PayPal'), ('fas fa-university', 'Transferência'), ('fas fa-money-bill-wave', 'Dinheiro'), ('fas fa-store', 'Local')], default='fas fa-credit-card', max_length=100),
        ),
    ]
