# Generated by Django 5.2.1 on 2025-11-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0004_alter_metodo_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='taxas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
