# Generated by Django 5.2.1 on 2025-10-21 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0002_categoria_icone_custom_categoria_icone_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, max_length=500)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('preco_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, max_length=500)),
                ('marca', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('cor', models.CharField(max_length=50)),
                ('disponivel', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, upload_to='photos/carros/')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.grupocarro')),
            ],
        ),
    ]
