# Generated by Django 5.2.1 on 2025-10-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='capacidade',
            field=models.IntegerField(default=None, help_text='Número de passageiros'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='combustivel',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('flex', 'Flex')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
