# Generated by Django 5.2.1 on 2025-11-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_carro_capacidade_carro_combustivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='combustivel',
        ),
        migrations.AddField(
            model_name='grupocarro',
            name='combustivel',
            field=models.CharField(choices=[('flex', 'Flex'), ('diesel', 'Diesel')], default='flex', max_length=50),
            preserve_default=False,
        ),
    ]
