# Generated by Django 5.2.8 on 2025-11-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carros", "0003_remove_carro_combustivel_grupocarro_combustivel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupocarro",
            name="combustivel",
            field=models.CharField(
                choices=[
                    ("flex", "Flex"),
                    ("diesel", "Diesel"),
                    ("eletrico", "Elétrico"),
                ],
                default="flex",
                max_length=50,
            ),
        ),
    ]
