# Generated by Django 5.2.7 on 2025-10-26 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0003_cupom_pagamento_cupom'),
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cupom',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='preco_total',
        ),
        migrations.AddField(
            model_name='reserva',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagamento.pagamento'),
        ),
    ]
