# Generated by Django 5.2.1 on 2025-11-16 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_reserva_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='updated_at',
            new_name='data_atualizacao',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='created_at',
            new_name='data_criacao',
        ),
    ]
