# Generated by Django 5.2.1 on 2025-11-18 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_rename_updated_at_reserva_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='desconto',
        ),
    ]
