# Generated by Django 5.2.1 on 2025-10-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icone_custom',
            field=models.CharField(blank=True, help_text='Digite qualquer emoji (ex: 🚀, ⚓, 🎯)', max_length=10, verbose_name='Emoji Personalizado'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='icone_tipo',
            field=models.CharField(choices=[('', '---------'), ('🚙', '🚙 Hatch/SUV'), ('🚗', '🚗 Sedan'), ('🛻', '🛻 Picape'), ('🏎️', '🏎️ Esportivo'), ('⚡', '⚡ Elétrico'), ('🚐', '🚐 Van'), ('🏍️', '🏍️ Moto'), ('custom', '✏️ Personalizado (digite abaixo)')], default='', max_length=10, verbose_name='Tipo de Ícone'),
        ),
    ]
